name: Get github workspace
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      env: dev
    steps:
      - name: Print all environment variables
        run: env
      - name: Example Step
        run: |
          ls -al ${{ github.workspace }}
          
      
